title: DDD Alliance
description: Bringing the Domain Driven Design community closer togehter
author: "DDD Alliance"

theme: minima

repository: jsanz/gh-pages-minima-starter

# Minima social links
github_username: ddd-alliance
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  social_links:
  - { platform: youtube, user_url: "https://www.youtube.com/@dddalliance" }
  - { platform: github, user_url: "https://www.youtube.com/ddd-alliance" }

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - .vscode
    - .devcontainer
